### ISSUE TITLE
GH Release announcement

### ISSUE THREAD

**Issue by phorcys420** [coder/codercord#2]
The release messages in [#releases](https://discord.com/channels/747933592273027093/984553991545446411/1067225872257515570) don't look so good, and @bpmct suggested that we show the changelog.

Since that requires having a custom implementation for GitHub releases, we might aswell make the embed better.

## Embed design
![image](https://user-images.githubusercontent.com/57866459/216977114-e0d4f20c-8f64-4f0e-9187-9c0f76f9d54b.png)
or
![image](https://user-images.githubusercontent.com/57866459/221374209-6b1b24d4-578a-4962-ace8-f4272d67cbcc.png)
(username will still be Codercord)

## Implementation 1
Feeding a custom webhook to the GH repo @ [coder/coder](https://github.com/coder/coder), I don't think we can really do that because it'd require us to expose a web server with a valid certificate and in the context of this project it might be a bit too overkill.

## Implementation 2
Requesting to the GitHub API frequently, I think this is not so reliable because it can be very delayed.

## Implementation 3 (preferred)
Using discord webhooks as a bridge, we could have a dummy channel that receives the gh stuff, then Codercord looks at new messages in that channel, then posts to [#releases](https://discord.com/channels/747933592273027093/984553991545446411/1067225872257515570), that would allow for the fastest announcements without having to expose a webhook.

**Comment by phorcys420** [comment]
I ended up using implementation 3 and the second release embed.

![image](https://github.com/coder/codercord/assets/57866459/3ebf8cf1-c18c-4e55-8ba3-bd83dc5c834d)

**Comment by bpmct** [comment]
Nice!
