### ISSUE TITLE
bug: bot does not send a release announcement if the last sent version number is higher than the current one

### ISSUE THREAD

**Issue by phorcys420** [coder/codercord#9]
While this was intentional at first, releases of mainline versions on coder/coder happen in parallel with stable ones, which means you can have v2.11.0, then v2.10.3, then v2.11.1, and so on.

This should be fixed, the embeds should also mention whether the release is mainline or stable to avoid confusion from users.

**Comment by phorcys420** [comment]
I'm rewriting this feature in the context of the TypeScript rewrite (#10) and I'm wondering if we really do want to fix this?
Do we really want to publish an announcement every time a mainline version is released?

Another question I had in mind, do we want to publish new versions of our other software? like code-server and envbuilder?

cc @matifali do you have an opinion on this?

**Comment by matifali** [comment]
I suggest we combine the mainline and stable announcement in 1 post and skip for patch releases. 

Also no need to announce other projects as this will be just noise.

**Comment by phorcys420** [comment]
Currently posting every release, will try to differentiate stable from security/patch releases in the future but as seen w/ Cian it's complicated w/ our current way of releasing things.

This has been moved out of the bot in favor of a [Zap](https://zapier.com/editor/269032470) to avoid having to expose a webhook.
